---
- name: Install httpd on the local server
  hosts: webserver
  become: true
  tasks:
  - name: Install httpd on web server
    yum:
      name: httpd
      state: present
  - name: Insert index page
    template:
      src: index.html
      dest: /var/www/html/index.html
  - name: start the httpd service
    service:
      name: httpd
      state: started
  - name: Enabling the httpd service
    service:
      name: httpd
      enabled: yes
  - name: open firewall for httpd
    command: firewall-cmd --zone=public --permanent --add-port=80/tcp
  - name: restart firewall
    command: firewall-cmd --reload
  - name: echo
    command: "echo HI there"
